### ISSUE TITLE
Make conflict resolution and rules configurable

### ISSUE THREAD

**Issue by vlsi** [jjohannes/java-ecosystem-capabilities#1]
E.g.:

a) If there's a mismatch of Guava versions, please fail instead of selecting something
b) Please don't add capabilities for `cglib`, because, well, it adds conflict

---

Looks like it might be configured in a Gradle extension, or there might be a "plugin per ecosystem" like `id("de.jjohannes.gradle:java-ecosystem-capabilities.cglib")`, `id("de.jjohannes.gradle:java-ecosystem-capabilities.guava")`, ...

**Comment by jjohannes** [comment]
Thanks for the feedback @vlsi. These are good points.

The idea with this plugin is that it provides rules all users in the Java ecosystem could agree on. Like `cglib` and `cgli-nodep` are the same thing in **every** context. So no one should have the need to deactivate it.

Of course that's theoretically, and maybe for some reason someone still dose not want it. 

Right now, there is always the possibility in Gradle to add another metadata rule that removes the capability again. You can stack these rules. So I could just document that and do nothing else as part of this plugin.

Or we allow disabling of rules via an extension. It is a practical problem with the timing in Gradle's configuration phase to conditionally (not) register a rule. But I think it could work if disabling means that a registered rule is deciding at rule execution time to do nothing.

Having a separate plugin for each rule sounds like this could blow up quickly. I imagine there are like several 100 more rules that could be added to this plugin. So if someone wants everything except for one rule, it would be very complicated to set things up. I think I would prefer the disabling of single rules then.

**Comment by jjohannes** [comment]
Suggestions for switches to offer on an extension:

### Turn off standard conflict resolution for a single capability

**Use case:** I want to make sure for certain complex cases (e.g. javax.mail) that I get notified when there is a conflict and I don't want the standard (largest version wins in this case) to kick in at all.

```
javaEcosystemCapabilities.deactivateResolutionStrategy("javax.mail:mail")
```

### Turn off standard conflict resolution (highest version wins) for all capabilities

**Use case:** I want to have full control myself. If there is a conflict, I want to know so that I can decide which component to pick. This is what you would have if the Capability metadata added by the plugin would actually be published.


```
javaEcosystemCapabilities.deactivateAllResolutionStrategies()
```

_Alternative_: Make deactivated the default, which might be good for many cases where you don't get so much conflicts and you want to control the few you have anyway. And then you can turn it on as convenience for cases where you just want the plugin to do "the best it can" for you(?)

### Turn off a single rule completely

**Use case:** This is an escape hatch if a rule give you trouble for some reason. It should not be needed normally.

```
javaEcosystemCapabilities.deactivateRule("javax.mail:mail")
```

**Comment by jjohannes** [comment]
Deactivating rules via an extension is not possible due to timing. As soon as a rule ist registered, it's parameters are _isolated_. Which means you can not pass a lazy parameter - e.g. `Provider<Boolean> active` - to a rule when registering it and then change it's value later through an extension.

Turning off rules completely was meant to be an escape hatch anyway. We should aim for having rules that can all be applied. Which would mean that they always cover components which have overlapping classes (same packages). Following this idea, `javax` vs `jakarta` rules will be adjusted in #6.

You can still "deactivate" a rule by adding another custom rule on top that removes a capability again:

```
    components.withModule(CGlibRule.MODULES[0]) {
        allVariants {
            withCapabilities {
                removeCapability(CGlibRule.CAPABILITY_GROUP, CGlibRule.CAPABILITY_NAME)
            }
        }
    }
```

It'll be possible though to deactivate the resolution strategy of single (or all) rules, if you only want the conflict and no auto-resolution.

```
// deactivate selected
javaEcosystemCapabilities {
    deactivatedResolutionStrategies.add(CGlibRule.CAPABILITY)
}

// deactivate all
javaEcosystemCapabilities {
    deactivatedResolutionStrategies.addAll(allCapabilities)
}
```

**Comment by boris-petrov** [comment]
@jjohannes thank you for the continued work on the plugin and the new version!

I couldn't find it in the changelog - what are the upgrade steps? One thing is that I removed `de.jjohannes.missing-metadata-guava` as it's now included in this plugin, correct?

As for the capabilities - I have this currently:

```gradle
resolutionStrategy.capabilitiesResolution {
	withCapability('javax.activation:activation') {
		def result = candidates.find { it.id.group == 'com.sun.activation' && it.id.module == 'jakarta.activation' }
		if (result != null) {
			select(result)
		}
	}

	withCapability('javax.annotation:jsr250-api') {
		def result = candidates.find { it.id.group == 'org.apache.tomcat' && it.id.module == 'tomcat-annotations-api' }
		if (result != null) {
			select(result)
		}
	}

	withCapability('javax.servlet:servlet-api') {
		def result = candidates.find { it.id.group == 'org.apache.tomcat' && it.id.module == 'tomcat-servlet-api' }
		if (result != null) {
			select(result)
		}
	}
}
```

Does this somehow change with the new version? Also, I can't seem to use `select('com.sun.activation:jakarta.activation:0')` because it doesn't exist in all cases when this capability is checked - I guess in some configurations `com.sun.activation:jakarta.activation` is missing. Is there something more clever I can do or this is the correct way to do it?

Thanks again!

**Comment by jjohannes** [comment]
Thanks for testing the new version @boris-petrov! I am working towards a `1.0` release and wanted to get some things that still annoyed me out of the way, before calling it `1.0`.

Yes you can just remove `de.jjohannes.missing-metadata-guava`. You are right that the upgrade path is not clear. I'll add something that'll warn you if you use both plugins together (added a note to #3 ).

Regarding `com.sun.activation:jakarta.activation`: I "relaxed" the rules for Javax/Jakarta because sometimes you might have the need to use both together during migration. Which is technically possible, because they have different packages. See detailed explanation here: https://github.com/jjohannes/java-ecosystem-capabilities/issues/6#issuecomment-1311312175 
This might unfortunaltely have broken some setups that worked with older versions (like yours).

As I wrote, there are now two capabilities to consider. One for `javax.activation:activation` and one for `jakarta.activation:jakarta.activation-api`. If you are already in the "Jakarta World", the capability to work on would be the Jakarta one. E.g.:

```
	withCapability('jakarta.activation:jakarta.activation-api') {
		select('com.sun.activation:jakarta.activation:0')
	}
}
```

There is also a constant now you can use: `JakartaActivationApiRule.CAPABILITY`

Nevertheless, I might still have broken something that worked bevore. Please let me know if you are not able to fix your setup. In that case, it would be very helpful if you can share a reproducer (and/or a Build Scan).

Thanks for taking the time to writeup the feedback.

**Comment by boris-petrov** [comment]
So, I'm still in the "javax world" because... reasons. :smile: Does what you say mean that now I **won't** get a conflict if some dependency of mine requires a `javax` dependency and another requires a `jakarta` one? That was the case until version 0.7 but since 0.7 that won't be an error any more, is that so?

If so, how can I get the "old" behavior? Do I have to add a `withCapability` for every Jakarta dependency and perhaps throw an exception or something?

As for my configuration - it works totally fine on the new version. But I guess it's not handling as many things now due to the changes you mentioned.

Thanks for the support!

**Comment by jjohannes** [comment]
You get a conflict, but only if the version of `com.sun.activation:jakarta.activation` does still contain the `javax` package. In the case of  _activation_ this is everything with version 1.x. In 2.x it switched to Jakarta and thus there is no longer a conflict (from the technical Java perspective, there are no duplicated classes).

The rule is considering this version barrier, where the package switched from `javax` to `jakarta`, now:
https://github.com/jjohannes/java-ecosystem-capabilities/blob/main/src/main/java/de/jjohannes/gradle/javaecosystem/capabilities/rules/JavaxActivationApiRule.java#L17

So in your case, if you get les conflicts now, I would check:
- How does the result differ? E.g. you can run `gradle <your-application-projct>:dependencies --configuration=runtimeClasspath > someFile.txt` for both cases and compare the text files.
- If you have more results now. E.g. a Jakarta version that is so high that it actually contains "jakarta" packages, there might be a potential issue - something depends on this higher version and with that on the "jakarta" package. The previous version of the plugin just "removed" this - which can then be a problem.

Unfortunately (as I tried to explain [here](https://github.com/jjohannes/java-ecosystem-capabilities/issues/6#issuecomment-1311312175)), I have no good idea right now how the plugin could help more with such situations.

What I would do in a situation like yours is define version constraints that reject higher versions of "Jakarta" libraries that you do not want to have. Then you'll get an error if they are pulled in transitively. Like here for example:

https://github.com/jjohannes/gradle-project-setup-howto/blob/main/gradle/platform/build.gradle.kts#L18-L21

```
dependencies.constraints {
    api("com.sun.mail:jakarta.mail:1.6.7") { version { reject("[2.0.0,)") } } // Upgrade to 2.x requires newer Jakarta APIs
    api("jakarta.inject:jakarta.inject-api:1.0.5") { version { reject("[2.0.0,)") } } // Upgrade to 2.x requires newer Jakarta APIs
    api("jakarta.servlet:jakarta.servlet-api:4.0.4") { version { reject("[5.0.0,)") } } // Stay Tomcat 8 compatible
}
```

**Comment by boris-petrov** [comment]
OK, forgive me for asking so many questions but I'm really not that familiar with Gradle capabilities and all...

So, let's start from the beginning - with version 0.7 you split the Javax/Jakarta rules. Is that *only* because you think people might need to use both together sometimes? 1) I'm not sure that's even the case - I can't imagine why anyone would want both `javax` and `jakarta` namespaces to exist at the same time for the same package; 2) with this didn't you break the vast majority of use-cases (like mine and #6) where people just one to have one or the other?

For me the end goal is simple - for now I'm stuck to Tomcat 9, so I'm still in `javax` world - hence I want **all** packages to be `javax`. If I have a transitive dependency that includes a `jakarta` package - I want that replaced with the equivalent `javax` one. When I migrate to Tomcat 10 - so the `jakarta` world - I want to change one line of configuration and that to replace **all** packages to be `jakarta` ones. And if I have a transitive dependency that includes a `javax` package - it to be replaced with the `jakarta` equivalent.

As far as I understood what version 0.6 did, it was pretty close to that, correct? The only part missing was the "switch"/one-liner that tells the plugin - I want only `javax` packages. Is this so? If so, for me 0.6 is more useful. The only thing I would add is that configuration option - like in the `logging-capabilities` plugin - where I can say `enforceLogback` and I forget about it. Here I would `enforceJavax` and that would set all constraints as they must be. But even without that switch I think it was pretty OK - I could manually add rules for all the capabilities to choose the package I want to be resolved. And the fact that the capabilities included *both* the `javax` and the `jakarta` packages is essential for that to work.

I'm not sure if what I say makes sense or if I'm not missing something really important that makes what I say here not possible.

Also, we might continue the discussion via email if you prefer to not "spam" so much the issues here.

**Comment by jjohannes** [comment]
@boris-petrov no problem. It's a confusing situation.

If you have a dependency that requires a version of Jakarta **with the jakarta package (!)** you cannot just remove that only because there is another version with the javax package. The code of that dependency was compiled against `jakarta.*` classes. These classes would be missing at runtime and the application fails. Version `0.6` of the plugin could create this situation, leading to a broken runtime classpath.

In such situations, you can potentially use `javax` and `jakarta` in parallel to satisfy all the requirements of your dependencies (hence the change in 0.7). Or you have to downgrade the dependency that requires the `jakarta` package such that it no longer requires it.

I Pushed a small sample (https://github.com/jjohannes/java-ecosystem-capabilities/commit/b37a517bfb7917294ce073d2f0e7cd2cb9f70cb9) demonstrating the problem with two dependencies:
- `org.apache.tomcat:tomcat-catalina:9.0.68` -> requires `javax` package
- `io.undertow:undertow-servlet:2.3.0.Final` -> requires `jakrata` package

Wit version `0.6` this sample -- `../../gradlew :run` -- fails with `NoClassDefFoundError: jakarta/servlet/UnavailableException`.

This plugin cannot provide a simple `force...()` because of that. It would have to rewrite code inside external Jars to make it compatible. Which is beyond the scope of this plugin.

**Comment by boris-petrov** [comment]
@jjohannes I see what you mean but I believe that these particular cases should not (be allowed to) happen. It's the same as if someone is still in `javax` world but also directly or transitively depends on `com.sun.activation:jakarta.activation` 2.x (which you mentioned above that is `jakarta`). That should be an error and should not be allowed. In this case people should depend on `jakarta.activation` 1.x and all would be fine. In your example, people shouldn't depend on the latest version of `io.undertow:undertow-servlet` but rather on some older one which is still `javax`. Same with `logback` for example. Version 1.4.x is `jakarta`, 1.3.x is `javax`. I still depend on 1.3.x and have forbidden 1.4.x because I don't want to mix the two worlds (which I guess leads to nothing good).

People should *only* have either `javax` or `jakarta`. That's my reasoning at least. Perhaps I'm not right in thinking that, not sure. But it has worked fine for me until now. If you make this plugin follow that "convention" it would 1) simplify the plugin itself; 2) allow for the `force...()` helpers and hence 3) simplify users of the plugin. Of course, I'm saying that looking from my perspective, perhaps there are others. But probably the (vast?) majority of people have the same case as me.

In the end, I'll go with whatever you decide is best. You've a much better understanding than me on Gradle stuff so I leave the hard decisions for you. :smile: Just please give examples somewhere on how one would configure my case (only `javax` or only `jakarta`) - it would help people (and me). :smile:

**Comment by jjohannes** [comment]
I agree that most of that would be great to have. I just wanted to clarify that `0.6` does not have such feature(s). It was doing the wrong thing (silently removing something that can lead to a runtime error as shown in the sample).

I would suggest to further discuss this on #6 where I already tried to explain that I think this cannot be solved only with _Capabilities_.  That the package was changed while keeping the same coordinates is just a bad situation to start with.

If you want the build to fail, as soon as a Jakarta thing comes in, I would suggest to add reject constraints as I proposed already:

```
dependencies.constraints {
    api("com.sun.mail:jakarta.mail:1.6.7") { version { reject("[2.0.0,)") } } // Upgrade to 2.x requires newer Jakarta APIs
    api("jakarta.inject:jakarta.inject-api:1.0.5") { version { reject("[2.0.0,)") } } // Upgrade to 2.x requires newer Jakarta APIs
    api("jakarta.servlet:jakarta.servlet-api:4.0.4") { version { reject("[5.0.0,)") } } // Stay Tomcat 8 compatible
}
```

There could be a plugin with a utility like `enforceJavax()` and then the plugin would add all these constraints for you. But then you should really have all the components/versions of Javax/Jakarta covered. Right now there is only a fraction of them in the rules. And I am not sure if this is in scope of this plugin (as this plugin is not only about Javax/Jakarta and this is beyond the pure capability/extending metadata topic).
However, I am happy to see further discussion (and maybe contribution) in the context of #6.
