### ISSUE TITLE
Missing `org.apache.tomcat:tomcat-annotations-api` artifact

### ISSUE THREAD

**Issue by boris-petrov** [jjohannes/java-ecosystem-capabilities#10]
Hi, thanks for the awesome initiative with this plugin!

I believe `org.apache.tomcat:tomcat-annotations-api` could be added to [JakartaAnnotationApiRule](https://github.com/jjohannes/java-ecosystem-capabilities/blob/main/plugin/src/main/java/de/jjohannes/gradle/javaecosystem/capabilities/rules/JakartaAnnotationApiRule.java).

Also `com.sun.activation:javax.activation` in [JakartaActivationApiRule](https://github.com/jjohannes/java-ecosystem-capabilities/blob/main/plugin/src/main/java/de/jjohannes/gradle/javaecosystem/capabilities/rules/JakartaActivationApiRule.java).

Also `com.sun.mail:javax.mail` to [JakartaMailApiRule](https://github.com/jjohannes/java-ecosystem-capabilities/blob/main/plugin/src/main/java/de/jjohannes/gradle/javaecosystem/capabilities/rules/JakartaMailApiRule.java).

Also, I'm not sure how these rules are supposed to work, but why doesn't [JakartaActivationApiRule](https://github.com/jjohannes/java-ecosystem-capabilities/blob/main/plugin/src/main/java/de/jjohannes/gradle/javaecosystem/capabilities/rules/JakartaActivationApiRule.java) contain `javax.activation:activation` in it (or is that implicitly coming from the capability's group and name)?

**Comment by jjohannes** [comment]
Thanks for pointing these out @boris-petrov. I will see that I add them. Unfortunately the whole Jakarta/Javax situation is very complex and has several dimensions. I am not so sure anymore where to head with these in this plugin 🙁 (see also #6).

**How are the rules supposed to work?**
I took the approach to ask: _"How would this look if the Capabilities would have been published in the metadata of the components?"_

Then, the _Capability Coordinates_ are defined by the first component that was every published with the capability. In the case of _activation_, the first published component is `javax.activation:activation`. We do not need to add the `javax.activation:activation` as Capability to that one, because [a component implicitly has the capability that corresponds to its own coordinates](https://docs.gradle.org/current/userguide/dependency_capability_conflict.html#capability_coordinates). So we only add the `javax.activation:activation` to all the other components that also have it but were published later (and could in theory have published this capability information).

**Comment by boris-petrov** [comment]
Thanks for the explanation about the capability coordinates, that clears things up!

As for the Jakarta/Javax situation... believe me, I know. :smile: I saw #6, yes, and I also would very much like to "choose" `javax` (as I still can't migrate to `jakarta`) and to have all dependencies follow that... but that's difficult and not *that* much needed. Actually what #1 requests is perhaps easier to implement in the plugin (you can say if that's true or not) and would almost do what #6 is about - people would just need to configure resolutions that set all dependencies to be `javax` or `jakarta`. That's actually what I personally did in my project and it works rather fine.

Keep your head up, this plugin that you wrote is great and is a very good approach to a very horrible problem. :)

**Comment by jjohannes** [comment]
Thanks for the encouragement!

I did the proposed extensions and publish `0.6`.
